### PR TITLE
fix typo litle -> little

### PR DESCRIPTION
**Pull request by bwo**

### CODE REVIEW

**Comment by VixieTSQ** [comment]
`awe` funnily enough is the correct spelling actually. `Aww` is an internet thing.

**Comment by wrac4242** [comment]
Hi, awe and aww are different words, I think you are thinking of aw and aww there
awe is "an emotion variously combining dread, veneration, and wonder that is inspired by authority or by the sacred or sublime" (webster dictionary)

**Comment by VixieTSQ** [comment]
> Hi, awe and aww are different words, I think you are thinking of aw and aww there awe is "an emotion variously combining dread, veneration, and wonder that is inspired by authority or by the sacred or sublime" (webster dictionary)

I swear I've heard otherwise... that's weird. I still wouldn't be surprised if aww came from awe. The definition for awe can still kinda make sense for what we use aww for.

**Comment by bwo** [comment]
“Awe”, which is a noun and not an interjection, is really not idiomatic in this context. “Aw” and “aww” are, but “aww” is more appropriate imo

**Comment by h4rldev** [comment]
It's been a month, why isn't this merged yet

**Comment by bwo** [comment]
mooooooom

**Comment by VixieTSQ** [comment]
> It's been a month, why isn't this merged yet

gankra hasn't looked at this repo AT ALL in the past month

**Comment by Gankra** [comment]
GANKRA MADE THIS IN A MANIC FEVERDREAM

GANKRA IS FULL OF CHAOS AGAIN

**Pull request merged**
