### PR TITLE
Randomized responses. Mommy has all sorts of differents things to tell you~

### PR DESCRIPTION
**Pull request by VixieTSQ**
I said I would spend days of my life on this. Day 1.

This PR adds line delimited files included into the binary at compile time with negative, and positive responses for mommy. For example, mommy will choose one line from the positive-responses.txt file if you've been a good girl for her, then replace the affectionate term placeholder (currently `AFFECTIONATE_TERM`) with your chosen affectionate term, then finally print it out.

There is some questions that should probably be answered sometime:

One is what guidelines should surround writing these responses? How NSFW are you allowed to get? Perhaps it should be an option for the user?  May you hard code gender neutral affectionate terms such as "sweetie"? Must all responses end with a `~ ❤️`? etc.

Another is about the use of placeholders. Do you have a better idea than just replacing every instance of `AFFECTIONATE_TERM`?

Another about newlines. You obviously can't have a response with a newline inside if the file is newline separated. Perhaps this is a good or acceptable limitation?

### CODE REVIEW

**Comment by Gankra** [comment]
line-separated files are a bit contrived in 2022 -- why not just make it a proper json file with an array of strings?

**Comment by VixieTSQ** [comment]
> line-separated files are a bit contrived in 2022 -- why not just make it a proper json file with an array of strings?

I liked the simplicity, but JSON it is! See my latest commit.

**Comment by nekodjin** [comment]
Or, better yet, a TOML file - though JSON is fine too :p

**Review by Gankra — APPROVED** [review]

**Comment by Gankra** [comment]
0.1.1 published, thanks! https://twitter.com/Gankra_/status/1605787689902432256

**Pull request merged**
